### ISSUE TITLE
Null pointer exception when navigating to localhost:8080/api/json in browser

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-hybrid-4j#6]
**Stack trace:**
```
23:09:01.714 [XNIO-1 task-9] E23nEHjxSZ2SLS1GvmSPAg ERROR c.n.exception.ExceptionHandler:64 handleRequest - Exception:
java.lang.NullPointerException: null
	at com.networknt.rpc.router.AbstractRpcHandler.getServiceId(AbstractRpcHandler.java:18)
	at com.networknt.rpc.router.JsonHandler$1.handle(JsonHandler.java:73)
	at io.undertow.io.AsyncReceiverImpl.receiveFullString(AsyncReceiverImpl.java:107)
	at io.undertow.io.AsyncReceiverImpl.receiveFullString(AsyncReceiverImpl.java:84)
	at com.networknt.rpc.router.JsonHandler.handleRequest(JsonHandler.java:61)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:126)
	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:67)
	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:62)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Server response:**

`{"statusCode":500,"code":"ERR10010","message":"RUNTIME_EXCEPTION","description":"Unexpected runtime exception"}
`

**Included jars:**
`codegen-web-1.3.0.jar`

**Comment by stevehu** [comment]
This is due to request body is empty. It is now handled properly to return a error message with 400 response code. Error code is ERR11201.
